# Utilise l'image de Node.js officielle comme image de base
FROM node:22

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et package-lock.json
COPY ../MyApp/GraphQLFinalProject/Front-End/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY ../MyApp/GraphQLFinalProject/Front-End .

# Exposer le port 5173 pour le frontend
EXPOSE 5173

# Démarrer l'application
CMD ["npm", "start"]
