- name: Configure EC2 instances
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - docker.io
        state: present

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone the Git repository
      git:
        repo: 'https://github.com/Julien-Somasundaram/AWS.git'
        dest: /home/ubuntu/AWS

- name: Initialize Docker Swarm (manager only)
  hosts: manager
  become: yes
  tasks:
    - name: Initialize Docker Swarm
      shell: docker swarm init
      register: swarm_init

    - name: Get Docker Swarm join-token (manager only)
      shell: docker swarm join-token -q worker
      register: join_token

    - name: Set swarm join token fact
      set_fact:
        swarm_join_token: "{{ join_token.stdout }}"

- name: Join the swarm (workers)
  hosts: workers
  become: yes
  tasks:
    - name: Leave current swarm if part of one
      shell: docker swarm leave --force
      ignore_errors: yes

    - name: Join the swarm
      shell: docker swarm join --token {{ hostvars[groups['manager'][0]].swarm_join_token }} {{ hostvars[groups['manager'][0]].ansible_default_ipv4.address }}:2377
      register: join_result
      retries: 5
      delay: 10
      until: join_result.rc == 0

- name: Deploy Docker stack
  hosts: manager
  become: yes
  tasks:
    - name: Deploy Docker stack
      shell: docker stack deploy -c /home/ubuntu/AWS/docker-stack.yml mystack
