version: '3.7'

services:
  backend:
    image: final-backend
    ports:
      - "4000:4000"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: final-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: final-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  database:
    image: final-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
